### ISSUE TITLE
Hidden Apps

### ISSUE THREAD

**Issue by GocalSD** [rgocal/Sapphyx_Launcher#12]
I can't find where did the apps go when I set them hidden, please help!!
And one more thing, how can I add apps in the blacklist of the app drawer?? 

Debug info:
 OS Version: 4.4.153-perf+(00WW_3_53B)
 OS API Level: 28
 Device: DRG_sprout
 Model (and Product): Nokia 6.1 Plus (Dragon_00WW)
 BRAND: Nokia
 HARDWARE: qcom
 MANUFACTURER: HMD Global

Extra Info: Sapphyx Launcher

**Comment by rgocal** [comment]
Join the telegram group for problems like this to be solved
